'use strict';

const fs = require('fs');
const path = require('path');
const os = require('os');
const { execSync } = require('child_process');

const TASK_NAME = 'ClaudeSync';
const CONFIG_DIR = path.join(os.homedir(), '.config', 'claude-sync');
const BAT_FILE = path.join(CONFIG_DIR, 'claude-sync-resurrect.bat');
const STARTUP_FOLDER = path.join(
  process.env.APPDATA || path.join(os.homedir(), 'AppData', 'Roaming'),
  'Microsoft', 'Windows', 'Start Menu', 'Programs', 'Startup'
);
const STARTUP_SHORTCUT_BAT = path.join(STARTUP_FOLDER, 'ClaudeSync.bat');

function getPm2CmdPath() {
  const pm2Cmd = path.join(__dirname, '..', 'node_modules', '.bin', 'pm2.cmd');
  if (fs.existsSync(pm2Cmd)) {
    return pm2Cmd;
  }
  try {
    const globalPm2 = execSync('where pm2.cmd', { encoding: 'utf8' }).trim().split('\n')[0].trim();
    if (globalPm2 && fs.existsSync(globalPm2)) {
      return globalPm2;
    }
  } catch {
    // not found globally
  }
  return null;
}

function createResurrectBat() {
  const pm2Cmd = getPm2CmdPath();
  if (!pm2Cmd) {
    return { success: false, error: 'Could not find pm2.cmd' };
  }

  if (!fs.existsSync(CONFIG_DIR)) {
    fs.mkdirSync(CONFIG_DIR, { recursive: true });
  }

  const batContent = [
    '@echo off',
    'REM ClaudeSync autostart - restores PM2 processes after login',
    'REM Generated by claude-sync. Do not edit manually.',
    'timeout /t 5 /nobreak >nul 2>&1',
    `"${pm2Cmd}" resurrect`,
  ].join('\r\n');

  fs.writeFileSync(BAT_FILE, batContent, 'utf8');
  return { success: true, batPath: BAT_FILE, pm2Cmd };
}

function pm2Save() {
  const pm2Cmd = getPm2CmdPath();
  if (!pm2Cmd) {
    return { success: false, error: 'Could not find pm2.cmd' };
  }

  try {
    execSync(`"${pm2Cmd}" save`, { encoding: 'utf8', stdio: 'pipe' });
    return { success: true };
  } catch (err) {
    return { success: false, error: err.message };
  }
}

function taskSchedulerEntryExists() {
  try {
    execSync(`schtasks /Query /TN "${TASK_NAME}"`, {
      encoding: 'utf8',
      stdio: 'pipe',
    });
    return true;
  } catch {
    return false;
  }
}

function createTaskSchedulerEntry(batPath) {
  if (taskSchedulerEntryExists()) {
    return { success: true, method: 'task-scheduler', skipped: true };
  }

  try {
    execSync(
      `schtasks /Create /TN "${TASK_NAME}" /TR "\\"${batPath}\\"" /SC ONLOGON /F`,
      { encoding: 'utf8', stdio: 'pipe' }
    );
    return { success: true, method: 'task-scheduler' };
  } catch (err) {
    return { success: false, error: err.message };
  }
}

function removeTaskSchedulerEntry() {
  if (!taskSchedulerEntryExists()) {
    return { success: true, skipped: true };
  }

  try {
    execSync(`schtasks /Delete /TN "${TASK_NAME}" /F`, {
      encoding: 'utf8',
      stdio: 'pipe',
    });
    return { success: true };
  } catch (err) {
    return { success: false, error: err.message };
  }
}

function createStartupFolderEntry(batPath) {
  if (fs.existsSync(STARTUP_SHORTCUT_BAT)) {
    return { success: true, method: 'startup-folder', skipped: true };
  }

  try {
    const content = [
      '@echo off',
      'REM ClaudeSync autostart via Startup folder',
      `call "${batPath}"`,
    ].join('\r\n');

    fs.writeFileSync(STARTUP_SHORTCUT_BAT, content, 'utf8');
    return { success: true, method: 'startup-folder' };
  } catch (err) {
    return { success: false, error: err.message };
  }
}

function removeStartupFolderEntry() {
  if (!fs.existsSync(STARTUP_SHORTCUT_BAT)) {
    return { success: true, skipped: true };
  }

  try {
    fs.unlinkSync(STARTUP_SHORTCUT_BAT);
    return { success: true };
  } catch (err) {
    return { success: false, error: err.message };
  }
}

function enableAutostart() {
  const saveResult = pm2Save();
  if (!saveResult.success) {
    return { success: false, error: `Failed to save PM2 state: ${saveResult.error}` };
  }

  const batResult = createResurrectBat();
  if (!batResult.success) {
    return { success: false, error: `Failed to create startup script: ${batResult.error}` };
  }

  const tsResult = createTaskSchedulerEntry(batResult.batPath);
  if (tsResult.success) {
    return { success: true, method: 'task-scheduler', skipped: tsResult.skipped || false };
  }

  const sfResult = createStartupFolderEntry(batResult.batPath);
  if (sfResult.success) {
    return {
      success: true,
      method: 'startup-folder',
      skipped: sfResult.skipped || false,
      warning: `Task Scheduler failed (${tsResult.error}). Using Startup folder instead.`,
    };
  }

  return { success: false, error: `Task Scheduler: ${tsResult.error}. Startup folder: ${sfResult.error}` };
}

function disableAutostart() {
  const warnings = [];

  const tsResult = removeTaskSchedulerEntry();
  if (!tsResult.success) {
    warnings.push(`Could not remove Task Scheduler entry: ${tsResult.error}`);
  }

  const sfResult = removeStartupFolderEntry();
  if (!sfResult.success) {
    warnings.push(`Could not remove Startup folder entry: ${sfResult.error}`);
  }

  try {
    if (fs.existsSync(BAT_FILE)) {
      fs.unlinkSync(BAT_FILE);
    }
  } catch (err) {
    warnings.push(`Could not remove startup script: ${err.message}`);
  }

  return { success: true, warnings };
}

module.exports = {
  enableAutostart,
  disableAutostart,
  getPm2CmdPath,
  taskSchedulerEntryExists,
  TASK_NAME,
  BAT_FILE,
  STARTUP_SHORTCUT_BAT,
};
